name: 'SSH into Environment'
on: [push]
jobs:
  master:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v1'
    - run: 'sudo apt-get install socat'
    - run: 'socat ''EXEC:curl -NsS https\://ppng.ml/xxxxxxxxxxxxxxxx!!EXEC:curl -NsST - https\://ppng.ml/yyyyyyyyyyyyyyyy'' TCP:127.0.0.1:22'
