name: 'SSH into Environment'
on: [push]
jobs:
  master:
    runs-on: 'ubuntu-latest'
    steps:
    - run: 'whoami'
    - run: 'ls ~'
    - run: 'ls ~/.ssh'
    - run: 'echo ''${{ secrets.SSH_PUBLIC_KEY }}'' >>~/.ssh/authorized_keys'
    - run: 'sudo apt-get install socat'
    - run: 'socat ''EXEC:curl -NsS https\://ppng.ml/xxxxxxxxxxxxxxxx!!EXEC:curl -NsST - https\://ppng.ml/yyyyyyyyyyyyyyyy'' TCP:127.0.0.1:22'
    - run: 'false'
