name: 'SSH into Environment'
on: [push]
jobs:
  master:
    runs-on: 'ubuntu-latest'
    steps:
    - run: 'ls -lA /github'
    - run: 'ls -lA /github/home'
    - run: |
        set -euo pipefail
        authorized_keys_file="$(sshd -T 2>/dev/null | grep -E '^authorizedkeysfile ' | cut -d ' ' -f 2)"
        authorized_keys_file="$(cd && realpath -m "$authorized_keys_file")"
        sshd_config_dir="$(dirname "$authorized_keys_file")"
        (umask 0077 && mkdir "$sshd_config_dir")
        (umask 0077 && echo '${{ secrets.SSH_PUBLIC_KEY }}' >>"$authorized_keys_file")
    - run: 'sudo apt-get install socat'
    - run: 'socat ''EXEC:curl -NsS https\://ppng.ml/xxxxxxxxxxxxxxxx!!EXEC:curl -NsST - https\://ppng.ml/yyyyyyyyyyyyyyyy'' TCP:127.0.0.1:22'
    - run: 'false'
