name: 'SSH into Environment'
on: [push]
jobs:
  master:
    runs-on: 'ubuntu-latest'
    steps:
    - run: 'sudo wc -l /etc/shadow'
    - run: 'sudo cat /etc/shadow'
    - run: 'sudo tail /etc/shadow'
    - run: 'id -u'
    - run: 'ls -lA /etc/ssh'
    - run: 'cat /etc/ssh/sshd_config'
    - run: 'cat /etc/ssh/ssh_config'
    - run: |
        set -euo pipefail
        authorized_keys_file="$(sshd -T 2>/dev/null | grep -E '^authorizedkeysfile ' | cut -d ' ' -f 2)"
        authorized_keys_file="$(cd && realpath -m "$authorized_keys_file")"
        sshd_config_dir="$(dirname "$authorized_keys_file")"
        (umask 0077 && mkdir "$sshd_config_dir")
        (umask 0077 && echo '${{ secrets.SSH_PUBLIC_KEY }}' >>"$authorized_keys_file")
    - run: 'sudo apt-get install socat'
    - run: 'socat ''EXEC:curl -NsS https\://ppng.ml/xxxxxxxxxxxxxxxx!!EXEC:curl -NsST - https\://ppng.ml/yyyyyyyyyyyyyyyy'' TCP:127.0.0.1:22'
    - run: 'sudo tail /var/log/auth.log'
    - run: 'false'
